#!/bin/bash

# 1. Make virtualenv
# 2. Patch pip in virtualenv
# 3. Install bzrlib in virtualenv.
# 4. Activate virtualenv
# 5. Make bundle in virtualenv using requirements/requirements-trunk.txt
# 6. Deactivate virtualenv
# 7. Optionally run l-d-t preview and ask for confirmation
# 8. Run l-d-t upgrade with bundle made in step 5.

set -uxe

def () {
    set +uxe;
    "$@";
    set -uxe;
}


LAVA_ROOT=/srv/lava
# Pip download cache
export PIP_DOWNLOAD_CACHE=$LAVA_ROOT/.downloads

LDT_DIR="$(dirname $(readlink -f $0))"
REQUIREMENTS="${LDT_DIR}/requirements/requirements-trunk.txt"
LDT="${LDT_DIR}/lava-deployment-tool"

SCRATCH_DIR="$(mktemp -d)"

trap "rm -rf \"${SCRATCH_DIR}\"" EXIT

VENV="${SCRATCH_DIR}/env"

virtualenv "${VENV}"

def . "${VENV}/bin/activate"

pip install -q -I https://github.com/zyga/pip/tarball/develop
pip install -q bzr

"${LDT}" bundle "${REQUIREMENTS}" "${SCRATCH_DIR}/lava.pybundle"

deactivate
